<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\FileLayout;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;
use Joomla\CMS\HTML\ModuleHelper;

# get the helper
use Joomla\CMS\Saa_helper\Saa_helper;
JLoader::register('Joomla\CMS\Saa_helper\Saa_helper', 'templates/street_art_aberdeen/html/saa_helper.php'); 

// Create shortcuts to some parameters.
$params  = $this->item->params;
$canEdit = $params->get('access-edit');
$user    = Factory::getUser();
$info    = $params->get('info_block_position', 0);
$htag    = $this->params->get('show_page_heading') ? 'h2' : 'h1';

// Check if associations are implemented. If they are, define the parameter.
$assocParam        = (Associations::isEnabled() && $params->get('show_associations'));
$currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;

JHtml::_('jquery.framework');

#echo "<pre>" . print_r($this->item, TRUE) . "</pre>";

if ( $this->item->catid == 9 ) {
	# it's an street art item

	$doc = JFactory::getDocument();
	$head_data = $doc->getHeadData();
	$head_data["metaTags"]["name"]["twitter:image"] = Uri::root() . Saa_helper::large_image( $this->item->jcfields[6]->rawvalue );
	$head_data["metaTags"]["property"]["og:image"] = Uri::root() . Saa_helper::large_image( $this->item->jcfields[6]->rawvalue );
	$doc->setHeadData($head_data);

	?>
<div class="com-content-article item-page<?php echo $this->pageclass_sfx; ?> container" itemscope itemtype="https://schema.org/Article">
	<?php if ($canEdit) : ?>
		<?php echo LayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item)); ?>
	<?php endif; ?>
	<div class="page-header">
		<<?php echo $htag; ?> itemprop="headline">
			<?php echo $this->escape($this->item->title); ?>
		</<?php echo $htag; ?>>
		<?php if ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JUNPUBLISHED'); ?></span>
		<?php endif; ?>
		<?php if ($isNotPublishedYet) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
		<?php endif; ?>
		<?php if ($isExpired) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JEXPIRED'); ?></span>
		<?php endif; ?>
	</div>
	<?php // Content is generated by content plugin event "onContentAfterTitle"?>
	<?php echo $this->item->event->afterDisplayTitle; ?>
	<div itemprop="articleBody" class="com-content-article__body">
		<?php echo $this->item->text; ?>
	</div>
	<?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
	<?php echo $this->item->event->beforeDisplayContent; ?>
	<?php // Content is generated by content plugin event "onContentAfterDisplay"?>
	<?php echo $this->item->event->afterDisplayContent; ?>
	<?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>
	<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>

	<?php
        $modules = JModuleHelper::getModules('article_below');
        foreach ($modules as $module) {
            $output = JModuleHelper::renderModule($module, array('style' => 'uncontained'));
            echo $output;
        }
	?>

	<?php 

	$user = Factory::getUser();
    if (!$user->guest) {
		# nearby
        echo "<h3>Other art nearby...</h3>\n";

		echo "<pre>" . print_r($this->item, TRUE) . "</pre>";

		list($this_lat, $this_lon) = explode(",", $this->item->jcfields[2]->rawvalue);
		echo "this_lat: " . $this_lat . " this_lon: " . $this_lon . "<br/>";

		$db = JFactory::getDbo();
		$query = $db->getQuery(true);
		$query->select( $db->quoteName( array('value', 'item_id'), array('ll', 'art_id') ) );
		$query->from($db->quoteName('#__fields_values'));
		$query->from($db->quoteName('#__content'));
		$query->where($db->quoteName('field_id') . ' = 2');
		$query->where($db->quoteName('item_id') . ' = ' . $db->quoteName('id'));
		$query->where($db->quoteName('item_id') . ' != ' . $db->quote( $this->item->id ));
		$query->where($db->quoteName('state') . ' = 1');
		#$query->order('ordering ASC');
		$db->setQuery($query);
		$ll_results = $db->loadObjectList();



		#echo "<pre>results: \n" . print_r($ll_results, TRUE) . "\n</pre>\n";

		$distance_array = Array();
		$art_lat = Array();
		$art_lon = Array();

		foreach ($ll_results AS $ll_result) {
			list($lat, $lon) = explode(",", $ll_result->ll);
			$lat_diff = abs($this_lat -  $lat);
			$lon_diff = abs($this_lon -  $lon);
			$diff = $lat_diff + $lon_diff;

			$distance_array[$ll_result->art_id] = $diff;

			$art_lat[$ll_result->art_id] = $lat;
			$art_lon[$ll_result->art_id] = $lon;

		}

		asort($distance_array);

		#echo "<pre>distance_array: \n" . print_r($distance_array, TRUE) . "\n</pre>\n";

		$distance_array = array_slice($distance_array, 0, 20, true); 
		
		echo "<pre>distance_array: \n" . print_r($distance_array, TRUE) . "\n</pre>\n";

		$close_items = array_keys( $distance_array );

		echo "<pre>close_items: \n" . print_r($close_items, TRUE) . "\n</pre>\n";

		$query = $db->getQuery(true);
		#$query->select( Array('c.id', 'c.title', 'c.alias', 'vp.value', 'vs.value'), Array('art_id', 'title', 'alias', 'photo', 'state'));
		$query->select( $db->quoteName('c.id', 'art_id') );
		$query->select( $db->quoteName('c.title', 'title') );
		$query->select( $db->quoteName('c.alias', 'alias') );
		#$query->select( $db->quoteName('vp.value', 'photo') ); 
		$query->select( $db->quoteName('vs.value', 'state') );
		#$query->from($db->quoteName('#__fields_values', 'vp'));
		$query->from($db->quoteName('#__fields_values', 'vs'));
		$query->from($db->quoteName('#__content', 'c'));
		#$query->where($db->quoteName('vp.field_id') . ' = 6');
		#$query->where($db->quoteName('vp.item_id') . ' = ' . $db->quoteName('id'));
		$query->where($db->quoteName('vs.field_id') . ' = ' . $db->quote(9));
		$query->where($db->quoteName('vs.item_id') . ' = ' . $db->quoteName('id'));
		$query->where($db->quoteName('c.id') . ' IN (' . implode(",", $close_items ) . ')' );
		$query->where($db->quoteName('c.state') . ' = 1');
		#$query->order('ordering ASC');
		$db->setQuery($query);
		$art_results = $db->loadObjectList();
		echo "<pre>query: " . $query . "</pre>\n";
		echo "<pre>number of art results: " . count($art_results) . "</pre>\n";
		echo "<pre>art_results: \n" . print_r($art_results, TRUE) . "\n</pre>\n";
		
		/*
https://streetartaberdeen.org/art/469



close_items: 
Array
(
    [0] => 142
    [1] => 144
    [2] => 145
    [3] => 127
    [4] => 146
    [5] => 147
    [6] => 288
    [7] => 148
    [8] => 375
    [9] => 309
    [10] => 376
    [11] => 307
    [12] => 286
    [13] => 308
    [14] => 278
    [15] => 277
    [16] => 106
    [17] => 380
    [18] => 382
    [19] => 379
)

query: 
SELECT `c`.`id` AS `art_id`,`c`.`title` AS `title`,`c`.`alias` AS `alias`,`vp`.`value` AS `photo`,`vs`.`value` AS `state`
FROM `#__fields_values` AS `vp`,`#__fields_values` AS `vs`,`#__content` AS `c`
WHERE `vp`.`field_id` = 6 AND `vp`.`item_id` = `id` AND `vs`.`field_id` = 9 AND `vs`.`item_id` = `id` AND `c`.`id` != '143' AND `c`.`id` IN (142,144,145,127,146,147,288,148,375,309,376,307,286,308,278,277,106,380,382,379) AND `c`.`state` = 1

art_results: 
Array
(
    [0] => stdClass Object
        (
            [art_id] => 278
            [title] => Near R G U Student Association, 60 Schoolhill, Aberdeen AB10 1JQ, UK
            [alias] => 610
            [photo] => images/image-field-file_id278_2022-01-20_16-33-54_4236.jpeg
            [state] => OK
        )

    [1] => stdClass Object
        (
            [art_id] => 148
            [title] => Near 18 Harriet Street, Aberdeen AB10 1FR, UK
            [alias] => 739
            [photo] => images/image-field-file_id148_2022-01-17_15-01-19_6318.jpeg
            [state] => OK
        )

    [2] => stdClass Object
        (
            [art_id] => 142
            [title] => Near 123B George St, Aberdeen AB25 1HU, UK
            [alias] => 946
            [photo] => images/image-field-file_id142_2022-01-17_14-51-55_5446.jpeg
            [state] => OK
        )

    [3] => stdClass Object
        (
            [art_id] => 307
            [title] => Near 7 Jopp's Ln, Aberdeen AB25 1BX, UK
            [alias] => 697
            [photo] => images/image-field-file_id307_2022-01-20_22-27-09_2567.jpeg
            [state] => OK
        )

)

Missing:
144,145,127,146,147,288,375,309,376,286,308,277,106,380,382,379

142,144,145,127,146,147,288,148,375,309,376,307,286,308,278,277,106,380,382,379

144 - https://streetartaberdeen.org/gallery/487

SELECT * FROM s3ib7_fields_values WHERE item_id=144
field_id	item_id		value	
2			144			57.14949407507846,-2.101724783646255	
3			144			Unknown	
1			144			Spray	
6			144			images/image-field-file_id144_2022-01-17_14-55-02_...	

SELECT * FROM s3ib7_fields_values WHERE item_id=307
field_id	item_id		value	
2			307			57.15101992781453,-2.101539001611039	
3			307			Unknown	
1			307			Stencil	
9			307			OK	
6			307			images/image-field-file_id307_2022-01-20_22-27-09_...	



SELECT `c`.`id` AS `art_id`,`c`.`title` AS `title`,`c`.`alias` AS `alias`,`vs`.`value` AS `state`
FROM `s3ib7_fields_values` AS `vs`,`s3ib7_content` AS `c`
WHERE `vs`.`field_id` = 9 AND `vs`.`item_id` = `id` AND `c`.`id` != '143' AND `c`.`id` IN (142,144,145,127,146,147,288,148,375,309,376,307,286,308,278,277,106,380,382,379) AND `c`.`state` = 1

SELECT * FROM s3ib7_content, s3ib7_fields_values WHERE id=item_id AND field_id=9 AND state=1;


SELECT COUNT(*) FROM s3ib7_fields_values WHERE field_id=9;	= 406
SELECT COUNT(*) FROM s3ib7_fields_values WHERE field_id=6;	= 727
SELECT COUNT(*) FROM s3ib7_fields_values WHERE field_id=1 	= 745

SELECT value, count(*) FROM s3ib7_fields_values WHERE field_id=9 GROUP BY value
value		count(*)	
Degraded	25	
Gone		34	
OK			347		


SELECT * FROM s3ib7_fields_values WHERE item_id=144;


*/

		JLoader::register('FieldsHelper', JPATH_ADMINISTRATOR . '/components/com_fields/helpers/fields.php');
		$custom_fields = FieldsHelper::getFields('com_content.article', $this->item, true);
		#echo "<pre>" . print_r($item, TRUE) . "</pre>";
		echo "<pre>custom_fields:\n" . print_r($custom_fields, TRUE) . "</pre>";

    }

	?>

</div>
	<?php 
} else {
	# it's a normal content item
    ?>
<div class="com-content-article item-page<?php echo $this->pageclass_sfx; ?> container" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? Factory::getApplication()->get('language') : $this->item->language; ?>">
	<?php if ($this->params->get('show_page_heading')) : ?>
	<div class="page-header">
		<h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
	</div>
	<?php endif;
    if (!empty($this->item->pagination) && !$this->item->paginationposition && $this->item->paginationrelative) {
        echo $this->item->pagination;
    } ?>

	<?php $useDefList = $params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
    || $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam; ?>

	<?php if ($params->get('show_title')) : ?>
	<div class="page-header">
		<<?php echo $htag; ?> itemprop="headline">
			<?php echo $this->escape($this->item->title); ?>
		</<?php echo $htag; ?>>
		<?php if ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JUNPUBLISHED'); ?></span>
		<?php endif; ?>
		<?php if ($isNotPublishedYet) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
		<?php endif; ?>
		<?php if ($isExpired) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JEXPIRED'); ?></span>
		<?php endif; ?>
	</div>
	<?php endif; ?>
	<?php if ($canEdit) : ?>
		<?php echo LayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item)); ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentAfterTitle"?>
	<?php echo $this->item->event->afterDisplayTitle; ?>

	<?php
	# sidebar on the left
    if (count(JModuleHelper::getModules('sidebar'))) {
        echo "<div class=\"sidebars\"> \n";
        $sidebars = JModuleHelper::getModules('sidebar');
        foreach ($sidebars as $sidebar) {
            $output = JModuleHelper::renderModule($sidebar, array('style' => 'noCard'));
            #$params = new JRegistry;
            #$params->loadString($sidebar->params);
            echo "<div class='sidebar'> \n";
            echo $output;
            echo "</div> \n";
        }
        echo "</div> \n";
    } 
	?>

	<?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
		<?php echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
	<?php endif; ?>

	<?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>

		<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
	<?php echo $this->item->event->beforeDisplayContent; ?>

	<?php if ((int) $params->get('urls_position', 0) === 0) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php if ($params->get('access-view')) : ?>
	<?php echo LayoutHelper::render('joomla.content.full_image', $this->item); ?>
	<?php
    if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) :
        echo $this->item->pagination;
    endif; ?>
	<?php if (isset($this->item->toc)) :
        echo $this->item->toc;
    endif; ?>
	<div itemprop="articleBody" class="com-content-article__body">
		<?php echo $this->item->text; ?>
	</div>

	<?php if ($info == 1 || $info == 2) : ?>
		<?php if ($useDefList) : ?>
			<?php echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
		<?php endif; ?>
		<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
			<?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>
			<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
		<?php endif; ?>
	<?php endif; ?>

	<?php
    if (!empty($this->item->pagination) && $this->item->paginationposition && !$this->item->paginationrelative) :
        echo $this->item->pagination; ?>
	<?php endif; ?>
	<?php if ((int) $params->get('urls_position', 0) === 1) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php // Optional teaser intro text for guests?>
	<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>
	<?php echo LayoutHelper::render('joomla.content.intro_image', $this->item); ?>
	<?php echo HTMLHelper::_('content.prepare', $this->item->introtext); ?>
	<?php // Optional link to let them register to see the whole article.?>
	<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
	<?php $menu = Factory::getApplication()->getMenu(); ?>
	<?php $active = $menu->getActive(); ?>
	<?php $itemId = $active->id; ?>
	<?php $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
	<?php $link->setVar('return', base64_encode(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
	<?php echo LayoutHelper::render('joomla.content.readmore', array('item' => $this->item, 'params' => $params, 'link' => $link)); ?>
	<?php endif; ?>
	<?php endif; ?>
	<?php
    if (!empty($this->item->pagination) && $this->item->paginationposition && $this->item->paginationrelative) :
        echo $this->item->pagination; ?>
	<?php endif; ?>
	<?php // Content is generated by content plugin event "onContentAfterDisplay"?>
	<?php echo $this->item->event->afterDisplayContent; ?>
</div>
<?php
}