<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\FileLayout;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;
use Joomla\CMS\HTML\ModuleHelper;

# get the helper
use Joomla\CMS\Saa_helper\Saa_helper;
JLoader::register('Joomla\CMS\Saa_helper\Saa_helper', 'templates/street_art_aberdeen/html/saa_helper.php'); 

// Create shortcuts to some parameters.
$params  = $this->item->params;
$canEdit = $params->get('access-edit');
$user    = Factory::getUser();
$info    = $params->get('info_block_position', 0);
$htag    = $this->params->get('show_page_heading') ? 'h2' : 'h1';

// Check if associations are implemented. If they are, define the parameter.
$assocParam        = (Associations::isEnabled() && $params->get('show_associations'));
$currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;

JHtml::_('jquery.framework');

#echo "<pre>" . print_r($this->item, TRUE) . "</pre>";

if ( $this->item->catid == 9 ) {
	# it's an street art item

	$doc = JFactory::getDocument();
	$head_data = $doc->getHeadData();
	$head_data["metaTags"]["name"]["twitter:image"] = Uri::root() . Saa_helper::large_image( $this->item->jcfields[6]->rawvalue );
	$head_data["metaTags"]["property"]["og:image"] = Uri::root() . Saa_helper::large_image( $this->item->jcfields[6]->rawvalue );
	$doc->setHeadData($head_data);

	?>
<div class="com-content-article item-page<?php echo $this->pageclass_sfx; ?> container" itemscope itemtype="https://schema.org/Article">
	<?php if ($canEdit) : ?>
		<?php echo LayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item)); ?>
	<?php endif; ?>
	<div class="page-header">
		<<?php echo $htag; ?> itemprop="headline">
			<?php echo $this->escape($this->item->title); ?>
		</<?php echo $htag; ?>>
		<?php if ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JUNPUBLISHED'); ?></span>
		<?php endif; ?>
		<?php if ($isNotPublishedYet) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
		<?php endif; ?>
		<?php if ($isExpired) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JEXPIRED'); ?></span>
		<?php endif; ?>
	</div>
	<?php // Content is generated by content plugin event "onContentAfterTitle"?>
	<?php echo $this->item->event->afterDisplayTitle; ?>
	<div itemprop="articleBody" class="com-content-article__body">
		<?php echo $this->item->text; ?>
	</div>
	<?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
	<?php echo $this->item->event->beforeDisplayContent; ?>
	<?php // Content is generated by content plugin event "onContentAfterDisplay"?>
	<?php echo $this->item->event->afterDisplayContent; ?>
	<?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>
	<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>

	<?php
        $modules = JModuleHelper::getModules('article_below');
        foreach ($modules as $module) {
            $output = JModuleHelper::renderModule($module, array('style' => 'uncontained'));
            echo $output;
        }
	?>

	<?php 
	# nearby
	echo "<h3>Other art nearby, the 20 closest...</h3>\n";

	#echo "<pre>" . print_r($this->item, TRUE) . "</pre>";

	list($this_lat, $this_lon) = explode(",", $this->item->jcfields[2]->rawvalue);
	#echo "this_lat: " . $this_lat . " this_lon: " . $this_lon . "<br/>";

	# get the lat & lon of all items
	$db = JFactory::getDbo();
	$query = $db->getQuery(true);
	$query->select( $db->quoteName( array('value', 'item_id'), array('ll', 'art_id') ) );
	$query->from($db->quoteName('#__fields_values'));
	$query->from($db->quoteName('#__content'));
	$query->where($db->quoteName('field_id') . ' = 2');
	$query->where($db->quoteName('item_id') . ' = ' . $db->quoteName('id'));
	$query->where($db->quoteName('item_id') . ' != ' . $db->quote( $this->item->id ));
	$query->where($db->quoteName('state') . ' = 1');
	$db->setQuery($query);
	$ll_results = $db->loadObjectList();
	#echo "<pre>results: \n" . print_r($ll_results, TRUE) . "\n</pre>\n";

	# get the diff for all items
	$distance_array = Array();
	$art_lat = Array();
	$art_lon = Array();
	foreach ($ll_results AS $ll_result) {
		list($lat, $lon) = explode(",", $ll_result->ll);
		$lat_diff = abs($this_lat -  $lat);
		$lon_diff = abs($this_lon -  $lon);
		$diff = $lat_diff + $lon_diff;
		$distance_array[$ll_result->art_id] = $diff;
		# save the lat & lon for later
		$art_lat[$ll_result->art_id] = $lat;
		$art_lon[$ll_result->art_id] = $lon;
	}

	# get all 'gone' items, and remove them from the list
	$query = $db->getQuery(true);
	$query->select( "item_id" );
	$query->from($db->quoteName('#__fields_values'));
	$query->where($db->quoteName('field_id') . ' = 9');
	$query->where($db->quoteName('value') . ' = ' . $db->quote('Gone'));
	$db->setQuery($query);
	$gone_articles = $db->loadColumn();
	foreach ( $gone_articles AS $gone_article ) {
		if ( array_key_exists($gone_article, $distance_array) ){
			unset( $distance_array[$gone_article] );
			#echo "<pre>unset gone article: " . $gone_article . " </pre>";
		}
	}

	# sort them by difference 
	asort($distance_array);
	# get the closest 20
	$distance_array = array_slice($distance_array, 0, 20, true); 
	# get the ID of all of the close ones	
	$close_items = array_keys( $distance_array );

	# get the details needed for the pins
	$query = $db->getQuery(true);
	$query->select( $db->quoteName('id') );
	$query->select( $db->quoteName('title', 'title') );
	$query->select( $db->quoteName('alias', 'alias') );
	$query->select( $db->quoteName('catid') ); 
	$query->select( $db->quoteName('value', 'photo') ); 
	$query->from($db->quoteName('#__fields_values'));
	$query->from($db->quoteName('#__content'));
	$query->where($db->quoteName('field_id') . ' = 6');
	$query->where($db->quoteName('item_id') . ' = ' . $db->quoteName('id'));
	$query->where($db->quoteName('id') . ' IN (' . implode(",", $close_items ) . ')' );
	$query->where($db->quoteName('state') . ' = 1');
	$db->setQuery($query);
	$art_results = $db->loadObjectList();

	# make up the map data
	$map_data = Array();
	foreach ( $art_results AS $art_result ) {
		$info_window_content = "<a href=\"/gallery/";
		$info_window_content .= $art_result->alias;			# TODO: make this use the route function
		$info_window_content .= "\" >";
		$info_window_content .= "<img src='" . Saa_helper::small_image( $art_result->photo ) . "' alt='" . $art_result->title . "' />";
		$info_window_content .= "</a>\n";
		$map_pin = Array(
			"id" => $art_result->id,
			"lat" => $art_lat[ $art_result->id ],
			"lon" => $art_lon[ $art_result->id ],
			"pin_image" => Saa_helper::pin_image( $art_result->photo ),
			"info_window_content" => $info_window_content,

		);
		$map_data[] = $map_pin;
	}

	#echo "<pre>map_data: " . print_r($map_data, TRUE) . "</pre>\n";
	?>
	<script>
	function init() {
		var mapOptions = {};
		var mapElement = document.getElementById('saa-nearby-map');
		var map = new google.maps.Map(mapElement, mapOptions);
		var bounds = new google.maps.LatLngBounds();
	<?php
	# loop through the places
	foreach ($map_data as $i => $map_pin) {
		
		if ( $map_pin["lat"] AND $map_pin["lon"] ) {
			?>
		var marker<?php echo $map_pin["id"]; ?> = new google.maps.Marker({
			position: {lat:<?php echo $map_pin["lat"]; ?>, lng: <?php echo $map_pin["lon"]; ?>}, 
			map: map,
			icon: {
				url: "<?php echo $map_pin["pin_image"]; ?>", 
				scaledSize: new google.maps.Size(60, 60),
			}
		});
		bounds.extend(marker<?php echo $map_pin["id"]; ?>.position);
		var infowindow<?php echo $map_pin["id"]; ?> = new google.maps.InfoWindow({
			content: <?php echo json_encode( $map_pin["info_window_content"] ); ?> ,map: map
		});
		marker<?php echo $map_pin["id"]; ?>.addListener('click', function () { 
			infowindow<?php echo $map_pin["id"]; ?>.open(map, marker<?php echo $map_pin["id"]; ?>) ;
		});
		infowindow<?php echo $map_pin["id"]; ?>.close();        
			<?php
		}    
	}
	
	?>

	const myLatLng = { lat: <?php echo $this_lat; ?>, lng: <?php echo $this_lon ?> };
	new google.maps.Marker({
		position: myLatLng,
		map,
		title: "This artwork is here",
	});

	map.fitBounds(bounds);

	markerMyLocation = new google.maps.Marker();
	const locationButton = document.createElement("button");
	locationButton.textContent = "Go to your current location";
	locationButton.classList.add("custom-map-control-button");
	locationButton.classList.add("btn");
	locationButton.classList.add("btn-primary");
	map.controls[google.maps.ControlPosition.LEFT_BOTTOM].push(locationButton);
	locationButton.addEventListener("click", () => {
		// Try HTML5 geolocation.
		if (navigator.geolocation) {
			navigator.geolocation.getCurrentPosition(
				(position) => {
					const pos = {
						lat: position.coords.latitude,
						lng: position.coords.longitude,
					};
					map.setCenter(pos);
					markerMyLocation.setPosition(pos);   
					markerMyLocation.setMap(map);      
				},
				() => {
						handleLocationError(true, markerMyLocation, map.getCenter());
					}
				);
			} else {
				// Browser doesn't support Geolocation
				handleLocationError(false, markerMyLocation, map.getCenter());
			}
		});
	};
	
	function handleLocationError(browserHasGeolocation, markerMyLocation, pos) {
		markerMyLocation.setPosition(pos);
		markerMyLocation.setContent(
			browserHasGeolocation
			? "Error: The Geolocation service failed."
			: "Error: Your browser doesn't support geolocation."
		);
		markerMyLocation.setMap(map);
	};
	
	google.maps.event.addDomListener(window, "resize", function() { 
		var center = map.getCenter(); 
		google.maps.event.trigger(map, "resize"); 
		map.setCenter(center); 
	});
	


	google.maps.event.addDomListener(window, 'load', init);
	</script>
	<div id='saa-nearby-map' style="height: 820px; width: 100%;"></div> 
	<?php


	?>

</div>
	<?php 
} else {
	# it's a normal content item
    ?>
<div class="com-content-article item-page<?php echo $this->pageclass_sfx; ?> container" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? Factory::getApplication()->get('language') : $this->item->language; ?>">
	<?php if ($this->params->get('show_page_heading')) : ?>
	<div class="page-header">
		<h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
	</div>
	<?php endif;
    if (!empty($this->item->pagination) && !$this->item->paginationposition && $this->item->paginationrelative) {
        echo $this->item->pagination;
    } ?>

	<?php $useDefList = $params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
    || $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam; ?>

	<?php if ($params->get('show_title')) : ?>
	<div class="page-header">
		<<?php echo $htag; ?> itemprop="headline">
			<?php echo $this->escape($this->item->title); ?>
		</<?php echo $htag; ?>>
		<?php if ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JUNPUBLISHED'); ?></span>
		<?php endif; ?>
		<?php if ($isNotPublishedYet) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
		<?php endif; ?>
		<?php if ($isExpired) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JEXPIRED'); ?></span>
		<?php endif; ?>
	</div>
	<?php endif; ?>
	<?php if ($canEdit) : ?>
		<?php echo LayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item)); ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentAfterTitle"?>
	<?php echo $this->item->event->afterDisplayTitle; ?>

	<?php
	# sidebar on the left
    if (count(JModuleHelper::getModules('sidebar'))) {
        echo "<div class=\"sidebars\"> \n";
        $sidebars = JModuleHelper::getModules('sidebar');
        foreach ($sidebars as $sidebar) {
            $output = JModuleHelper::renderModule($sidebar, array('style' => 'noCard'));
            #$params = new JRegistry;
            #$params->loadString($sidebar->params);
            echo "<div class='sidebar'> \n";
            echo $output;
            echo "</div> \n";
        }
        echo "</div> \n";
    } 
	?>

	<?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
		<?php echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
	<?php endif; ?>

	<?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>

		<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
	<?php echo $this->item->event->beforeDisplayContent; ?>

	<?php if ((int) $params->get('urls_position', 0) === 0) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php if ($params->get('access-view')) : ?>
	<?php echo LayoutHelper::render('joomla.content.full_image', $this->item); ?>
	<?php
    if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) :
        echo $this->item->pagination;
    endif; ?>
	<?php if (isset($this->item->toc)) :
        echo $this->item->toc;
    endif; ?>
	<div itemprop="articleBody" class="com-content-article__body">
		<?php echo $this->item->text; ?>
	</div>

	<?php if ($info == 1 || $info == 2) : ?>
		<?php if ($useDefList) : ?>
			<?php echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
		<?php endif; ?>
		<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
			<?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>
			<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
		<?php endif; ?>
	<?php endif; ?>

	<?php
    if (!empty($this->item->pagination) && $this->item->paginationposition && !$this->item->paginationrelative) :
        echo $this->item->pagination; ?>
	<?php endif; ?>
	<?php if ((int) $params->get('urls_position', 0) === 1) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php // Optional teaser intro text for guests?>
	<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>
	<?php echo LayoutHelper::render('joomla.content.intro_image', $this->item); ?>
	<?php echo HTMLHelper::_('content.prepare', $this->item->introtext); ?>
	<?php // Optional link to let them register to see the whole article.?>
	<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
	<?php $menu = Factory::getApplication()->getMenu(); ?>
	<?php $active = $menu->getActive(); ?>
	<?php $itemId = $active->id; ?>
	<?php $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
	<?php $link->setVar('return', base64_encode(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
	<?php echo LayoutHelper::render('joomla.content.readmore', array('item' => $this->item, 'params' => $params, 'link' => $link)); ?>
	<?php endif; ?>
	<?php endif; ?>
	<?php
    if (!empty($this->item->pagination) && $this->item->paginationposition && $this->item->paginationrelative) :
        echo $this->item->pagination; ?>
	<?php endif; ?>
	<?php // Content is generated by content plugin event "onContentAfterDisplay"?>
	<?php echo $this->item->event->afterDisplayContent; ?>
</div>
<?php
}