<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\FileLayout;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;
use Joomla\CMS\HTML\ModuleHelper;

# get the helper
use Joomla\CMS\Saa_helper\Saa_helper;
JLoader::register('Joomla\CMS\Saa_helper\Saa_helper', 'templates/street_art_aberdeen/html/saa_helper.php'); 

// Create shortcuts to some parameters.
$params  = $this->item->params;
$canEdit = $params->get('access-edit');
$user    = Factory::getUser();
$info    = $params->get('info_block_position', 0);
$htag    = $this->params->get('show_page_heading') ? 'h2' : 'h1';

// Check if associations are implemented. If they are, define the parameter.
$assocParam        = (Associations::isEnabled() && $params->get('show_associations'));
$currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;

JHtml::_('jquery.framework');

#echo "<pre>" . print_r($this->item, TRUE) . "</pre>";

if ( $this->item->catid == 9 ) {
	# it's an street art item

	$doc = JFactory::getDocument();
	$head_data = $doc->getHeadData();
	$head_data["metaTags"]["name"]["twitter:image"] = Uri::root() . Saa_helper::large_image( $this->item->jcfields[6]->rawvalue );
	$head_data["metaTags"]["property"]["og:image"] = Uri::root() . Saa_helper::large_image( $this->item->jcfields[6]->rawvalue );
	$doc->setHeadData($head_data);

	?>
<div class="com-content-article item-page<?php echo $this->pageclass_sfx; ?> container" itemscope itemtype="https://schema.org/Article">
	<?php if ($canEdit) : ?>
		<?php echo LayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item)); ?>
	<?php endif; ?>
	<div class="page-header">
		<<?php echo $htag; ?> itemprop="headline">
			<?php echo $this->escape($this->item->title); ?>
		</<?php echo $htag; ?>>
		<?php if ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JUNPUBLISHED'); ?></span>
		<?php endif; ?>
		<?php if ($isNotPublishedYet) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
		<?php endif; ?>
		<?php if ($isExpired) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JEXPIRED'); ?></span>
		<?php endif; ?>
	</div>
	<?php // Content is generated by content plugin event "onContentAfterTitle"?>
	<?php echo $this->item->event->afterDisplayTitle; ?>
	<div itemprop="articleBody" class="com-content-article__body">
		<?php echo $this->item->text; ?>
	</div>
	<?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
	<?php echo $this->item->event->beforeDisplayContent; ?>
	<?php // Content is generated by content plugin event "onContentAfterDisplay"?>
	<?php echo $this->item->event->afterDisplayContent; ?>
	<?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>
	<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>

	<?php
        $modules = JModuleHelper::getModules('article_below');
        foreach ($modules as $module) {
            $output = JModuleHelper::renderModule($module, array('style' => 'uncontained'));
            echo $output;
        }
	?>

	<?php 
	$user = Factory::getUser();
    if (!$user->guest) {
		# nearby
        echo "<h3>Other art nearby...</h3>\n";

		list($this_lat, $this_lon) = explode(",", $this->item->jcfields[2]->rawvalue);
		echo "this_lat: " . $this_lat . " this_lon: " . $this_lon . "<br/>";

		$db = JFactory::getDbo();
		$query = $db->getQuery(true);
		$query->select( $db->quoteName( array('value', 'item_id'), array('ll', 'art_id') ) );
		$query->from($db->quoteName('#__fields_values'));
		$query->from($db->quoteName('#__content'));
		$query->where($db->quoteName('field_id') . ' = 2');
		$query->where($db->quoteName('item_id') . ' = ' . $db->quoteName('id'));
		$query->where($db->quoteName('item_id') . ' != ' . $db->quote( $this->item->id ));
		$query->where($db->quoteName('state') . ' = 1');
		$query->order('ordering ASC');
		$db->setQuery($query);
		$ll_results = $db->loadObjectList();



		#echo "<pre>results: \n" . print_r($ll_results, TRUE) . "\n</pre>\n";

		$distance_array = Array();
		$art_lat = Array();
		$art_lon = Array();

		foreach ($ll_results AS $ll_result) {
			list($lat, $lon) = explode(",", $ll_result->ll);
			$lat_diff = abs($this_lat -  $lat);
			$lon_diff = abs($this_lon -  $lon);
			$diff = $lat_diff + $lon_diff;

			$distance_array[$ll_result->art_id] = $diff;

			$art_lat[$ll_result->art_id] = $lat;
			$art_lon[$ll_result->art_id] = $lon;

		}

		asort($distance_array);

		$distance_array = array_slice($distance_array, 0, 20); 
		
		echo "<pre>distance_array: \n" . print_r($distance_array, TRUE) . "\n</pre>\n";

		$close_items = array_keys( $distance_array );

		$query = $db->getQuery(true);
		$query->select( 'c.id', 'c.title', 'c.alias', 'vp.value');
		$query->from($db->quoteName('#__fields_values', 'vp'));
		$query->from($db->quoteName('#__fields_values', 'vs'));
		$query->from($db->quoteName('#__content', 'c'));
		$query->where($db->quoteName('vp.field_id') . ' = 6');
		$query->where($db->quoteName('vp.item_id') . ' = ' . $db->quoteName('id'));
		$query->where($db->quoteName('c.id') . ' != ' . $db->quote( $this->item->id ));
		$query->where($db->quoteName('c.id') . ' IN (' . implode(",", $close_items ));
		$query->where($db->quoteName('c.state') . ' = 1');
		$query->order('ordering ASC');
		$db->setQuery($query);
		$ll_results = $db->loadObjectList();


    }
	?>

</div>
	<?php 
} else {
	# it's a normal content item
    ?>
<div class="com-content-article item-page<?php echo $this->pageclass_sfx; ?> container" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? Factory::getApplication()->get('language') : $this->item->language; ?>">
	<?php if ($this->params->get('show_page_heading')) : ?>
	<div class="page-header">
		<h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
	</div>
	<?php endif;
    if (!empty($this->item->pagination) && !$this->item->paginationposition && $this->item->paginationrelative) {
        echo $this->item->pagination;
    } ?>

	<?php $useDefList = $params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
    || $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam; ?>

	<?php if ($params->get('show_title')) : ?>
	<div class="page-header">
		<<?php echo $htag; ?> itemprop="headline">
			<?php echo $this->escape($this->item->title); ?>
		</<?php echo $htag; ?>>
		<?php if ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JUNPUBLISHED'); ?></span>
		<?php endif; ?>
		<?php if ($isNotPublishedYet) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
		<?php endif; ?>
		<?php if ($isExpired) : ?>
			<span class="badge bg-warning text-light"><?php echo Text::_('JEXPIRED'); ?></span>
		<?php endif; ?>
	</div>
	<?php endif; ?>
	<?php if ($canEdit) : ?>
		<?php echo LayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item)); ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentAfterTitle"?>
	<?php echo $this->item->event->afterDisplayTitle; ?>

	<?php
	# sidebar on the left
    if (count(JModuleHelper::getModules('sidebar'))) {
        echo "<div class=\"sidebars\"> \n";
        $sidebars = JModuleHelper::getModules('sidebar');
        foreach ($sidebars as $sidebar) {
            $output = JModuleHelper::renderModule($sidebar, array('style' => 'noCard'));
            #$params = new JRegistry;
            #$params->loadString($sidebar->params);
            echo "<div class='sidebar'> \n";
            echo $output;
            echo "</div> \n";
        }
        echo "</div> \n";
    } 
	?>

	<?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
		<?php echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
	<?php endif; ?>

	<?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>

		<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
	<?php echo $this->item->event->beforeDisplayContent; ?>

	<?php if ((int) $params->get('urls_position', 0) === 0) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php if ($params->get('access-view')) : ?>
	<?php echo LayoutHelper::render('joomla.content.full_image', $this->item); ?>
	<?php
    if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) :
        echo $this->item->pagination;
    endif; ?>
	<?php if (isset($this->item->toc)) :
        echo $this->item->toc;
    endif; ?>
	<div itemprop="articleBody" class="com-content-article__body">
		<?php echo $this->item->text; ?>
	</div>

	<?php if ($info == 1 || $info == 2) : ?>
		<?php if ($useDefList) : ?>
			<?php echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
		<?php endif; ?>
		<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
			<?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>
			<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
		<?php endif; ?>
	<?php endif; ?>

	<?php
    if (!empty($this->item->pagination) && $this->item->paginationposition && !$this->item->paginationrelative) :
        echo $this->item->pagination; ?>
	<?php endif; ?>
	<?php if ((int) $params->get('urls_position', 0) === 1) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php // Optional teaser intro text for guests?>
	<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>
	<?php echo LayoutHelper::render('joomla.content.intro_image', $this->item); ?>
	<?php echo HTMLHelper::_('content.prepare', $this->item->introtext); ?>
	<?php // Optional link to let them register to see the whole article.?>
	<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
	<?php $menu = Factory::getApplication()->getMenu(); ?>
	<?php $active = $menu->getActive(); ?>
	<?php $itemId = $active->id; ?>
	<?php $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
	<?php $link->setVar('return', base64_encode(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
	<?php echo LayoutHelper::render('joomla.content.readmore', array('item' => $this->item, 'params' => $params, 'link' => $link)); ?>
	<?php endif; ?>
	<?php endif; ?>
	<?php
    if (!empty($this->item->pagination) && $this->item->paginationposition && $this->item->paginationrelative) :
        echo $this->item->pagination; ?>
	<?php endif; ?>
	<?php // Content is generated by content plugin event "onContentAfterDisplay"?>
	<?php echo $this->item->event->afterDisplayContent; ?>
</div>
<?php
}